"""Canonical domain models — PRD §4.2. Pure Pydantic, no database, no network."""

from fc.models.command import (
    CUT_VERBS,
    READ_ONLY_VERBS,
    WRITE_VERBS,
    CommandPayload,
    CommandVerb,
    ParsedCommand,
    RuleDraft,
)
from fc.models.exception_ import (
    AUTO_SAFE,
    NEVER_AUTO,
    Cluster,
    Exception_,
    ExceptionCategory,
    ExceptionStatus,
    ResolvedBy,
    RuleApplicationRef,
    Tier,
)
from fc.models.ids import ULID_LENGTH, deterministic_factory, new_ulid
from fc.models.match import (
    FUZZY_CONFIDENCE_CAP,
    ConfidenceDerivation,
    MatchEvidence,
    MatchResult,
    MatchStage,
)
from fc.models.money import RUPEE, already_paise, fmt_inr, to_paise
from fc.models.rule import (
    Deduction,
    DeductionBasis,
    DeductionStackItem,
    DeductionType,
    Rule,
    RuleApplication,
    RuleOrigin,
    RuleOutcome,
    RuleStatus,
    Scope,
    Tolerance,
)
from fc.models.transaction import Direction, Source, TransactionEvent

__all__ = [
    "AUTO_SAFE",
    "CUT_VERBS",
    "FUZZY_CONFIDENCE_CAP",
    "NEVER_AUTO",
    "READ_ONLY_VERBS",
    "RUPEE",
    "ULID_LENGTH",
    "WRITE_VERBS",
    "Cluster",
    "CommandPayload",
    "CommandVerb",
    "ConfidenceDerivation",
    "Deduction",
    "DeductionBasis",
    "DeductionStackItem",
    "DeductionType",
    "Direction",
    "ExceptionCategory",
    "ExceptionStatus",
    "Exception_",
    "MatchEvidence",
    "MatchResult",
    "MatchStage",
    "ParsedCommand",
    "ResolvedBy",
    "Rule",
    "RuleApplication",
    "RuleApplicationRef",
    "RuleDraft",
    "RuleOrigin",
    "RuleOutcome",
    "RuleStatus",
    "Scope",
    "Source",
    "Tier",
    "Tolerance",
    "TransactionEvent",
    "already_paise",
    "deterministic_factory",
    "fmt_inr",
    "new_ulid",
    "to_paise",
]
